config/routes.rb
Rails.application.routes.draw do

  scope :csv do
    match 'export' => 'contacts#export_csv', via: [:get, :post], as: :csv_export
    match 'import' => 'contacts#import_csv', via: [:get, :post], as: :csv_import
  end

  resources :contacts, path: '/' do

    match 'share' => 'contacts#share', via: [:get, :post], as: :share

    resource :phones
    resource :emails

  end



end

app/models/contact.rb
class Contact < ActiveRecord::Base

  has_many :phones, :dependent => :destroy
  has_many :emails, :dependent => :destroy
  attr_accessor :recipient
  validates :first_name, uniqueness: { scope: :last_name, message: I18n.t('errors.first_last_names_must_be_unique')}

  before_save :check_name_unique

  def name
    "#{first_name} #{last_name}"
  end

  def self.import(file)
    result = {imported: 0, updated: 0}
    begin
      csv_data = file.read
      if csv_data.length > 0
        csv_rows = CSV.parse(csv_data).rotate
        csv_rows.each do |contact_csv_data|
          contact_id = contact_csv_data[0]
          unless contact_id.eql? 'id'
            contact = find_by_id(contact_id)
            contact_data = extract_csv_data(contact_csv_data)
            if contact
              result[:updated] += 1
              contact.update_attributes(contact_data.slice(:first_name, :last_name))
              contact.phones.find_or_create_by(number: contact_data[:phone])
              contact.emails.find_or_create_by(email: contact_data[:email])
            else
              result[:imported] += 1
              contact = Contact.create(contact_data.slice(:first_name, :last_name))
              if contact
                contact.phones.find_or_create_by(number: contact_data[:phone])
                contact.emails.find_or_create_by(email: contact_data[:email])
              end
            end
          end

        end
      end
    rescue Exception => e
      logger.info "Exception #{e.inspect}"
    end

    return result
  end

  def self.extract_csv_data(raw_data)
    return {first_name: raw_data[1], last_name: raw_data[2], phone: raw_data[5], email: raw_data[6]} if raw_data.size >= 7
    return {}
  end

  def self.to_csv(options = {})
    begin
      CSV.generate(options) do |csv|
        csv << ["id", "first_name", "last_name", "created_at", "updated_at", "phone", "email"]
        logger.info "#{csv}"
        all.each do |contact|
          values = contact.attributes.values_at(*column_names)
          values << contact.phones.first.number
          values << contact.emails.first.email
          csv << values
        end
      end
    rescue Exception => e
      logger.info "Exception #{e.inspect}"
    end

  end

  def check_name_unique
    if Contact.where(first_name: first_name, last_name: last_name).length > 0
      errors.add(:base, I18n.t('errors.first_last_names_must_be_unique'))
      return false
    end
    return true
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy, :share]

  #
  # Export/Import CSV
  def export_csv
    @contacts = Contact.all

    respond_to do |format|
      format.csv { send_data @contacts.to_csv ,  filename: "contacts-#{Date.today}.csv"  }
    end
  end

  def import_csv
    @contacts_count = {imported: 0, updated: 0}
    if request.post?
      file = csv_as_data(params)

      @contacts_count = Contact.import(file)
    end
  end

  #
  # Share
  def share
    ContactMailer.share_contact(@contact, params[:contact][:recipient]).deliver_later
    redirect_to :back
  end

  def index
    @contacts = Contact.all
  end

  def create
    @contact = Contact.new(contact_params)

    if check_contact_params and @contact.save
      @contact.emails.create(email_params)
      @contact.phones.create(phone_params)

      flash_it(:notice, t('success.contact_successfully_created'))
    else
      flash_it(:error, t('errors.phone_and_email_must_be_presented'))
    end

    respond_to do |format|
      if not @contact.new_record?
        format.html { redirect_to @contact}
      else
        format.html { render action: 'new', notice: flash[:notice], error: flash[:error] }
      end
    end

  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def show
  end

  def update
    if request.patch? and @contact
      if @contact.update_attributes(contact_params)
        flash_it(:notice, t('success.contact_updated'))
      else
        flash_it(:error, t('errors.cant_update_contact'))
        flash[:error] += @contact.errors.full_messages
      end
    end

    redirect_to contact_path(@contact)
  end

  def destroy
    if @contact.destroy
      flash_it(:notice, t('success.contact_successfully_destroyed'))
    end
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: flash[:notice], error: flash[:error] }
    end
  end


  private


  def csv_as_data(params)
    if params.has_key? :contact and params[:contact].has_key? :csv_file
      csv_file_param = params.require(:contact).permit(:csv_file)
      return csv_file_param[:csv_file]
    end
    return nil
  end
  def set_contact
    @contact = Contact.find(params[:id]) if params.has_key? :id
    @contact = Contact.find(params[:contact_id]) if params.has_key? :contact_id
  end

  def check_contact_params
    return false if not phone_params.has_key? :number or phone_params[:number].length <= 0
    return false if not email_params.has_key? :email  or email_params[:email].length <= 0

    return true
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name)
  end

  def phone_params
    params.require(:contact).require(:phone).permit(:number)
  end

  def email_params
    params.require(:contact).require(:email).permit(:email)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper


end

app/views/contacts/create.html.slim
h1 Contacts#create
p Find me in app/views/contacts/create.html.slim

app/views/contacts/destroy.html.slim
h1 Contacts#destroy
p Find me in app/views/contacts/destroy.html.slim

app/views/contacts/edit.html.slim
h1 Edit Contact for #{@contact.name}

= form_for(@contact) do |contact_form|
  = contact_form.label :first_name
  = contact_form.text_field :first_name
  br
  = contact_form.label :last_name
  = contact_form.text_field :last_name
  br



  = submit_tag

app/views/contacts/export_csv.html.slim
Export csv

app/views/contacts/import_csv.html.slim
Import csv
hr
Imported
b
  | Imported #{@contacts_count[:imported]}
br
b
  | Updated #{@contacts_count[:updated]}

hr
= form_for(:contact, :html => { :multipart => true }) do |f|
  = f.file_field(:csv_file)
  br
  = f.submit t('action.import_csv')

app/views/contacts/index.html.slim
h1 Contacts list
= link_to t('export_to_csv'), csv_export_path(format: :csv)
= link_to t('import_from_csv'), csv_import_path

- unless @contacts.empty?
  table#table
    thead
      tr
        td id
        td = t('models.contact.first_name')
        td = t('models.contact.last_name')
        td = t('models.contact.phones')
        td = t('models.contact.emails')
        td = t('global.actions')

    - @contacts.each do |contact|
      tr
        td = contact.id
        td = contact.first_name
        td = contact.last_name
        td = contact.phones.count
        td = contact.emails.count
        td
          = link_to t('action.edit'), edit_contact_path(contact)
          br
          = link_to t('actions.view'), contact_path(contact)
          br
          = link_to t('actions.share_by_mail'), contact_share_path(contact)
          br
          = link_to t('actions.new_phone'), new_contact_phones_path(contact)
          br
          = link_to t('actions.new_email'), new_contact_emails_path(contact)
          br
          = link_to t('actions.destroy'), contact_path(contact), {method: :delete}

app/views/contacts/new.html.slim
h1 New contact

= form_for(@contact) do |contact_form|
  = contact_form.label :first_name
  = contact_form.text_field :first_name
  br
  = contact_form.label :last_name
  = contact_form.text_field :last_name
  br

  = contact_form.fields_for :phone do |phone|
    = phone.label :number
    = phone.text_field :number

  br
  = contact_form.fields_for :email do |email|
    = email.label :email
    = email.text_field :email



  = submit_tag

app/views/contacts/show.html.slim
h1 Contact #{@contact.id} for #{@contact.name}

- if @contact.errors.full_messages.count > 0
  hr
  - @contact.errors.full_messages.each do |error_message|
    b = error_message


= link_to t('action.edit'), edit_contact_path(@contact)
br
= link_to t('actions.share_by_mail'), contact_share_path(@contact)
br
= link_to t('actions.new_phone'), new_contact_phones_path(@contact)
br
= link_to t('actions.new_email'), new_contact_emails_path(@contact)
br
= link_to t('actions.destroy'), contact_path(@contact), {method: :delete}
hr
h3 Share
= form_for(@contact, {url: contact_share_path(contact_id: @contact.id), method: :post}) do |f|
 = f.text_field :recipient
 = f.submit t('action.share')
hr
h3 Phones
table
  thead
    tr
      td id
      td = t('global.phone_number')
      td = t('global.actions')
  - @contact.phones.each do |phone|
    tr
      td = phone.id
      td = phone.number
      td
        = link_to t('actions.delete'), contact_phones_url(@contact, id: phone.id), {method: :delete}


hr
h3 Emails
table
  thead
    tr
      td id
      td = t('global.email')
      td = t('global.actions')
  - @contact.emails.each do |email|
    tr
      td = email.id
      td = email.email
      td
        = link_to t('actions.delete'), contact_emails_url(@contact, id: email.id), {method: :delete}

app/views/contacts/update.html.slim
h1 Contacts#update
p Find me in app/views/contacts/update.html.slim